### ISSUE TITLE
Add dev stage to build pipeline

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe-cluster-testbench#100]
It would be nice if we could test changes before deploying them.

Adapt build pipeline to:
- add a build parameter whether changes should be deployed to dev environment
- build a dev image
- deploy dev image to dev environment

**Comment by pihme** [comment]
@Zelldon Checkout branch `100-add-dev-stage`

It is not integrated into the build pipeline yet. 

However, there is a new namespace `testbench-dev` in our cluster where we can deploy test installations. 

The branch contains deployment descriptors for testbench and chaos-worker. These descriptors have settings which point to.
* a cluster on Dev (https://237f9938-e974-4f5d-9494-d42a7d8fac1f.operate.dev.ultrawombat.com/) 
* a different slack channel to publish to
* a different Google Sheet to write to

So anything we deploy in that will run without interfering without the live testbench.

Like I said, it isn't integrated into the build pipeline yet. So we need to deploy things manually. But it is a start for a more decoupled devlopment.

**Comment by pihme** [comment]
Next I am looking for a way to copy the image build and deploy steps without copying all the shell code. Any ideas?

**Comment by Zelldon** [comment]
> Next I am looking for a way to copy the image build and deploy steps without copying all the shell code. Any ideas?

Not sure in which context you're currently but maybe you can create a function which you can call ?

**Comment by pihme** [comment]
I want to parameterize the deploy stage of the build pipeline to build images either tagged with `latest` or `dev` and then to either deploy to dev or int depending on the deploy target.
