### ISSUE TITLE
Evaluate whether it makes sense to replace chaos worker scripts with python

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-testbench#110]
Currently the chaos worker is completely written in bash script, which might make it hard to maintain, since not everyone is familiar with it. We currently use bats to test the scripts.

For the first approach it was easier and fast to get something working. But to be a bit more future proven it might make sense to replace it with another language implementation like python, since chaostoolkit is also written in python.

**Comment by pihme** [comment]
Yes please. I don't think the zbctl version is gonna cut it.

**Comment by Zelldon** [comment]
We have now a kotlin worker which executes the scripts, soon some of them will be replaced as well.
