### ISSUE TITLE
Job handler doesn't exit after namespace is not found

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-testbench#115]
We have extra logic which handles problems when the namespace is not found, but somehow it doesn't work as expected

Source: https://github.com/zeebe-io/zeebe-cluster-testbench/blob/master/core/chaos-workers/handleJob.sh#L39
```
kubens "$NAMESPACE" &>> "$logFile" || (echo "{\"testResult\":\"FAILED\"}" && exit 1)
```

The script moves forward it seems, at least I can see job completion with two failed messages.

**Comment by pihme** [comment]
not really a problem
