### ISSUE TITLE
Add variable "root workflow" to daily test run, qa protocol

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe-cluster-testbench#125]
Currently it is hard to find out which root process led to the execution of a certain test.

This could be remedied by setting a variable "root workflow" (or something like this) in the root workflows.
Current root workflows are:
- Daily Tests
- QA Protocol

**Comment by Zelldon** [comment]
funny is that our records contain this information but operate doesn show that :see_no_evil:
