### ISSUE TITLE
Scale chaos worker

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-testbench#150]
Currently we run with one chaos worker, which runs all chaos experiments for one cluster plan at a time. This is necessary to avoid concurrency in executing the chaos experiments and writting to the logs and changing resources/contexts etc.

What we could do is to use a statefulset and scale it. This means we would have for each pod an own pvc and each worker can run for a cluster plan, which makes parallelism possible.

Down side is to get the logs you need to find them on the different pvc's. Alternative we use one pvc and write always to unique logs. 

\cc @pihme

**Comment by pihme** [comment]
Could we write the cluster ID into the log? Then we could download all and look for the cluster ID?

**Comment by Zelldon** [comment]
we use multiple threads with https://github.com/zeebe-io/zeebe-cluster-testbench/pull/284#issuecomment-816671590
