### ISSUE TITLE
Show in Google Test Result sheet the Test name

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-testbench#153]
Currently in the test sheet it is not visible which test has been exeucted would cool to have this info as a separate column.

**Comment by pihme** [comment]
duplicate of #124

**Comment by Zelldon** [comment]
Ah sorry have overseen this

**Comment by pihme** [comment]
yeah, the issues list is getting a little long for my liking. I will do some culling
