### ISSUE TITLE
Update wait-for-result to zbctl 0.26.0

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe-cluster-testbench#194]
**Description**

See original issue: https://github.com/zeebe-io/zeebe/issues/6008. With https://github.com/zeebe-io/zeebe/pulls/5972 the output of `zbctl` activate jobs is now always a JSON array, so we need to use array access to extract the keys.

**Comment by pihme** [comment]
There is nothing really to do here. The only thing that one could change - more for consistency is `/scripts/wait-for-result.sh` This script is never called. It is more like a template. This version of the script doesn't reflect the change to return an array. So one could look at how we do it in Jenkins and then modify the script.
