### ISSUE TITLE
When no business key is present, the layout in test report sheet is off

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe-cluster-testbench#203]
For daily tests the business key is empty. In the test report this leads to the following columns moving up one column to the left and the layout is broken.

This seems to be a general issue with empty cells, and it seems it changed with one of the recent updates to the Sheet API.

Solution:
- have a helper function that translates null values into "n/a" and pass all values through that helper function

**Comment by pihme** [comment]
![image](https://user-images.githubusercontent.com/14032870/103918244-d4696100-510e-11eb-9d32-380e0dd53182.png)

**Comment by npepinpe** [comment]
I wonder what the reason is for this behaviour (assuming it's not a bug, of course) :thinking:
