### ISSUE TITLE
Deploy pipeline broken 

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe-cluster-testbench#222]
Deploy pipeline currently fails with the following error:

```
[2021-01-25T08:49:18.599Z] Updated property [core/project].
[2021-01-25T08:49:19.701Z] + gcloud config set compute/region europe-west1
[2021-01-25T08:49:20.290Z] Updated property [compute/region].
[2021-01-25T08:49:42.965Z] ERROR: (gcloud.config.set) Some requests did not succeed:
[2021-01-25T08:49:42.966Z]  - Required 'compute.regions.list' permission for 'projects/zeebe-io'
[2021-01-25T08:49:42.966Z] 
script returned exit code 1
```
https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/zeebe-io%2Fzeebe-cluster-testbench/detail/master/216/pipeline

**Comment by npepinpe** [comment]
It seems the service account used has only container management permissions (so `container.`, nothing `compute.*`). Did we change service accounts? If not, then maybe infra changed the permissions.

**Comment by pihme** [comment]
Not aware of any changes.

**Comment by pihme** [comment]
Note from Infra: 
```
Hey, from what I can see it’s about a ServiceAccount in the Google project of zeebe-io, which we as Infra don’t have access to and thereby can’t change anything. Previous Zeebe DRI had access but afaik they didn’t change anything.
````

**Comment by pihme** [comment]
Further hints from Infra:


I figured it out and have multiple suggestions to you of how to fix it.
Edit the podspec and switch over to gcr.io/google.com/cloudsdktool/cloud-sdk since https://hub.docker.com/r/google/cloud-sdk is deprecated from march
please always define a full version as tag and not just latest/slim/alpine since you won’t have any control if they introduce a breaking change
323.0.0-slim works as expected 324.0.0-slim introduced a breaking change and requires you to be logged in prior, so either change that or use the suggested image for now.
Hope it is helpful, let me know if it works
