### ISSUE TITLE
Delete Cluster worker should be idempotent

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe-cluster-testbench#223]
I encountered an incident due to 404 on DELETE cluster. 

The incident in the workflow instance
![Screenshot 2021-01-25 at 14 28 10](https://user-images.githubusercontent.com/3511026/105712001-8ed3d300-5f19-11eb-9c07-bff0f5b2e9a4.png)

The incident details:
![Screenshot 2021-01-25 at 14 29 20](https://user-images.githubusercontent.com/3511026/105712155-b9be2700-5f19-11eb-8241-2416dc2b7dcb.png)

I think this did not have to be an incident. When the worker tries to delete the cluster and it is not there, then this is actually the same as it's intended result. 

**Expected behaviour**
The worker should complete the job successfully when receiving 404 on DELETE cluster.

**Comment by pihme** [comment]
Happened again today. 

Also currently we can only cancel the process as this is a dead end.

**Comment by pihme** [comment]
Implementation hints:

The class to make the change in is `DeleteClusterInCamundaCloudHandler` 

The communication with the cloud API is abstracted in the `CloudAPIClient`

The easiest way to realize the change is to call `cloudApiClient.listClusterInfos()` and check whether the cluster is still there.

It is also possible to react to the 404 when calling `deleteCluster(clusterId)`. However, I am not entirely sure how the 404 manifests itself in terms of the ReastEasy response binding. It might be thrown as a nice exception, or it might also arrive as a "Could not parse response" kind of exception. If the exception is not nice, one possibility is to implement something akin to `BadRequestResponseFilter` and throw a nicer exception.

In terms of testing, it would be good to add a unit test that verifies the interaction with mocked objects. There are several test implementation classes which already do something like that.
