### ISSUE TITLE
Multi-version support

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe-cluster-testbench#251]
**Goal**
* have different versions of the testbench running side-by-side. Each version is tied to a Zeebe version (with the expectation that we have one testbench version per major version of Zeebe)

**Steps**
***House Keeping***
* rename master branch to develop
* create branch to capture 0.26 state

***Create new testbench cluster instance for develop***
* maybe in production
* Follow all cluster-specific steps in https://github.com/zeebe-io/zeebe-cluster-testbench/blob/master/docs/operator-handbook.md
* Complete https://github.com/zeebe-io/zeebe-cluster-testbench/pull/249
* Adjust version of referenced zbtcl artifact in chaos workers
* Think about naming conventions for this version and future versions (naming convention could cover: branch, secrets files, namespace in Kubernetes, Docker image names)
* Create secrets in Vault that point to the new cluster (respect naming conventions)
* Create namespace in zeebe-io google cloud for the new workers (respect naming conventions)
* Adjust Jenkinsfile
  * introduce concept of stable branches (very much like we have for Zeebe)
  * retrieve secrets for the right version 
  * Maybe decide on target namespace here and pass it into deployment scripts
* Adjust deployment  scripts (either select right namespace here, or pass in namespace from Jenknsfile)
* Adjust Jenkinsfile in Zeebe
   * Adjust timer trigger: not just for develop, but for develop and stable branches
   * When RUN_QA is set explicitly, we need to figure out which testbench to talk to, based on the Zeebe verssion
   * Pick the right secrets file to talk to the right testbench
* Maybe hard-code image version into daily test protocol BPMN model
* Maybe add version guard to models 
* Add to documentation to explain all this

***Open Issues*** 
* What to do with current dev stage

**Comment by korthout** [comment]
@pihme Let's discuss whether this is done, or we still need to do something

**Comment by korthout** [comment]
Still todo:
- Update `Testbench 1.x Dev` to 1.0.0
- (maybe) Remove daily test
- (maybe) version guard in models - once we actually have this problem
- add versions/branches description to Developer Handbook

**Comment by korthout** [comment]
Still todo:
- ~Update `Testbench 1.x Dev` to 1.0.0~
- ~(maybe) Remove daily test~ - will not do now, not necessary for full multi-version support
- ~(maybe) version guard in models~ - once we actually have this problem
- add versions/branches description to Developer Handbook
