### ISSUE TITLE
Create testbench orchestration cluster for develop branch

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe-cluster-testbench#255]
* Think about naming conventions for this version and future versions (naming convention could cover: branch, secrets files, namespace in Kubernetes, Docker image names)
* Create cluster by following the cluster specific steps in https://github.com/zeebe-io/zeebe-cluster-testbench/blob/master/docs/operator-handbook.md
* Create secrets in Vault that point to the new cluster (respect naming conventions) https://confluence.camunda.com/display/HAN/CI+Secrets+Self-Service
* Create namespace in zeebe-io google cloud for the new workers (respect naming conventions)

**Comment by pihme** [comment]
Naming convention:

Pattern: `[product]-[major version].x`
Example: `testbench-1.x`

(`x` indicates any minor version)

Pattern2: `[product]-[symbolic version]`
Example `testbench-develop`

**Comment by pihme** [comment]
On second thought, the orchestration cluster for the develop branch cannot be in production. It needs to be on integration stage, because only there the latest development version of the software is available. Otherwise we run into the same problem which led us down this path.

**Comment by korthout** [comment]
@pihme Production has alpha channels available as well. So this should be fine right?

**Comment by korthout** [comment]
Cluster [366794ec-0b11-4954-b9c6-f971aba45536](https://console.cloud.camunda.io/org/4dbcec38-3a39-449f-aa9d-a08336972074/cluster/366794ec-0b11-4954-b9c6-f971aba45536) created in organization [Zeebe + Operate Team
](https://console.cloud.camunda.io/org/4dbcec38-3a39-449f-aa9d-a08336972074)

**Comment by korthout** [comment]
Addition to the naming convention: postfix the staging type

Development of the testbench is done on `[product]-[major version].x-dev` while real use happens on `[product]-[major version].x-prod`. For 1.x that translates to: `testbench-1.x-dev` and `testbench-1.x-prod`

**Comment by korthout** [comment]
Namespaces `testbench-1-x-dev` and `testbench-1-x-prod` created in `zeebe-io` gke.

> namespaces may not contain dots `.`.
