### ISSUE TITLE
Extend Jenkins pipeline to be mindful of version

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe-cluster-testbench#257]
* Adjust Jenkinsfile 
  *  introduce concept of stable branches (very much like we have for Zeebe)
  *  retrieve secrets for the right version
  *  Maybe decide on target namespace here and pass it into deployment scripts
* Adjust deployment scripts (either select right namespace here, or pass in namespace from Jenknsfile)

**Comment by korthout** [comment]
Already done as part of #255 with #270
