### ISSUE TITLE
Remove daily tests

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe-cluster-testbench#324]
Daily tests and nightly QA runs are redundant. Since nightly QA runs give more control over which version is being tested, I propose to remove the daily test protocols.

**Comment by korthout** [comment]
Do we already have a go on this?

**Comment by pihme** [comment]
Not sure @npepinpe had had time to look at it and make up his mind yet

**Comment by npepinpe** [comment]
Sorry, it completely slipped off my radar. Let's drop the daily tests and keep only the nightly QA

**Comment by korthout** [comment]
I have stopped both daily tests (on 0.26 and 1.0). But we can't undeploy the daily test process. Shall I overwrite it with a new empty version to make sure no-one restarts it?

**Comment by pihme** [comment]
Yes, please. Also, when you redeploy the empty version: 
* please change the name to "Legacy - "
![image](https://user-images.githubusercontent.com/14032870/121654757-597deb00-ca9e-11eb-88a7-076412a2e560.png)
(in Testbench 0.26)
* Remove the content from the docs
