### ISSUE TITLE
Improve log messages for workers

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe-cluster-testbench#344]
Currently all workers write to the same log stream. This makes it difficult to filter for e.g. all log messages related to a certain worker and related to a certain cluster.

One improvement would be to use MDC https://dzone.com/articles/mdc-better-way-of-logging-1 to also log metadata
* which worker produced the log
* Which cluster is being tested
* Which process instance (in testbench) triggered the worker

We could then make this information available to StackDriver, similarly to what we do in Zeebe.

**Comment by pihme** [comment]
see #363 for implementation for chaos workers; same needs to be done for none-chaos workers as well.

**Comment by Zelldon** [comment]
Make sure that you set the MDC to all threads https://github.com/zeebe-io/zeebe-cluster-testbench/commit/6ead6e0858833085b43e05c98923ba5dc407f312 since it is a thread local thing
