### ISSUE TITLE
Add cluster UUID to slack message

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe-cluster-testbench#345]
Currently the slack message for a failure only contains the cluster name. Often we need the UUID for the cluster. Putting this UUID directly into the message would save a lookup.

**Comment by Zelldon** [comment]
@pihme is https://github.com/zeebe-io/zeebe-cluster-testbench/pull/353 enought for that or do you also want it for the other tests ?

**Comment by pihme** [comment]
I would like to have it for all tests, preferably by changing `NotifyEngineersHandler`.
