### ISSUE TITLE
HumanTask is no longer supported by Tasklist

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-testbench#367]
The taskType `humanTask` which we use in our analyse cluster process is no not a supported task type, so it will not be picked by by a Tasklist 1.0.

https://github.com/zeebe-io/zeebe-cluster-testbench/blob/3dfdae330f9a56d69d3643d3798bdf05ba2970fd/processes/analyse-cluster.bpmn#L31

**Comment by korthout** [comment]
Should be resolved with #390
