### ISSUE TITLE
Backport latest chaos worker changes to 0.26

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-testbench#370]
We did several improvements for the stackdriver logging and context which should be backported to 0.26.

**Comment by Zelldon** [comment]
* https://github.com/zeebe-io/zeebe-cluster-testbench/pull/365
 * https://github.com/zeebe-io/zeebe-cluster-testbench/pull/366
 * https://github.com/zeebe-io/zeebe-cluster-testbench/pull/369
 * https://github.com/zeebe-io/zeebe-cluster-testbench/commit/6ead6e0858833085b43e05c98923ba5dc407f312

**Comment by npepinpe** [comment]
imo can be closed now :+1:
