### ISSUE TITLE
Daily tests should run on the latest patch version 

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe-cluster-testbench#376]
The process [Daily Test](https://github.com/zeebe-io/zeebe-cluster-testbench#daily-test) is created with a given generation. It runs the tests always against the given version. 

If a new bugfix of this version is released then it still runs the tests against the old version. If the old version is removed in the cloud then the process fails because it can't create a cluster for the old version.

Currently, we need to update the variable "generation" manually to run the tests against the new version.

We should either automate the process of update the variable or make it part of the release procedure.

**Comment by pihme** [comment]
I would rather suggest to remove daily tests altogether: #324

**Comment by pihme** [comment]
Daily tests have been removed
