### ISSUE TITLE
Remove 0.26 Testbench

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-testbench#423]
With the newest 1.1.0 release we no longer support 0.26, which means we can remove our Testbench 0.26

**Comment by Zelldon** [comment]
Lets summarize what we need to do here @pihme @korthout I will write down things I think we need to do maybe you have more or different approach.

 * delete stable branch (0.26)
 * delete jenkins job (?)
 * delete testbench 0.26 namespace in zeebe gke
 * delete testbench 0.26 Camunda cloud cluster

**Comment by pihme** [comment]
My two cents on this:

* there is no Jenkins job to delete
* I would propose to keep resources re-activatable. I know we don't support 0.26 anymore, but if a customer comes, I would like to be able to reactivate everything. This means I would keep the stable branch, and I would drain the namespace, but keep the namespaces in zeebe gke (assuming an empty namespace costs no money).
* For cloud clusters we need to delete two - the productive and the dev cluster

**Comment by korthout** [comment]
Please note that I've disabled testbench 0.26 for now. Due to problems with the create-cluster worker.

I've disabled it using:
```
kubectx gke_zeebe-io_europe-west1-b_zeebe-cluste
kubens testbench
kubectl scale deployment testbench --replicas 0
```

**Comment by pihme** [comment]
Repeated the scale down after auto-deploy reactivated everything:
```
kubectl scale deployment testbench --replicas 0
kubectl scale deployment chaos-worker --replicas 0
```

**Comment by pihme** [comment]
@npepinpe Any objections to removing 0.26 testbench? If not, I would clean this up as part of my medic duty this week

**Comment by npepinpe** [comment]
No, let's remove it. The last 0.26 patch is out already, we don't need to run Testbench on this branch anymore.

**Comment by pihme** [comment]
@saig0 FYI - I will delete the 0.26 clusters now

**Comment by Zelldon** [comment]
Btw @pihme I dont think you need to keep the k8 namespace, since namespaces are easy to create :)
