### ISSUE TITLE
Update Testbench clusters to 1.1.0 discussion

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe-cluster-testbench#438]
The `Testbench 1.x Dev` and `Testbench 1.x Prod` cluster need to updated to 1.1.0. I think we can just do this, but I'd like to discuss it here before we take any action.

AFAIK, 1.0.1 is fully forwards compatible with 1.1.0. After the upgrade, the clusters are available in the `bru-1` region. I don't think the client needs to be changed, but perhaps I'm wrong. I'd love to here what you think.

**Comment by korthout** [comment]
ping @pihme @Zelldon

**Comment by pihme** [comment]
From my side it's a go. Will be interesting to see whether we need to modify the client.

**Comment by korthout** [comment]
There were quite a lot of chaos test failures on testbench last weekend. Let's discuss with the next medic during handover whether this would conflict
