### ISSUE TITLE
Testbench run currently with outdated cluster plans

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-testbench#439]
Currently we run tests with "old" T-Shirt sizes, which seem to become out dated. Only old customers will run with this configuration. New ones are getting a new cluster plan, which we currently not test. We should change that. 

New cluster plan is called: `GA Hardware Package` 

@ultraschuppi idea was to run against all available cluster plans to be sure.
@menski mentioned we can more or less ignore the the old tshirt sizes.

Maybe @npepinpe @pihme @korthout has an opinion

related slack discussion: https://camunda.slack.com/archives/CT702EPFH/p1625772818086800

**Comment by ultraschuppi** [comment]
just to clarify: new **signups** will get the new GA Hardware Package plan and all professional orgs resulting out of them have that

however - all existing pre-GA paying orgs still run on the tshirt size model.

so it is not really outdated, as new clusters generated by those pre-ga-paying orgs are still getting tshirt size based clusters

**Comment by npepinpe** [comment]
What's the long term plan there? Keep things as is, or do we want to (somehow) have these customers migrate to the new plans?

**Comment by Zelldon** [comment]
I think for that they need to migrate the org, which is I think not easily possible? (As far as I understood @ultraschuppi ) The old org have no access to the new cluster plan. At least that was on int. @ultraschuppi hacked that a bit such that the `Zeebe Operate Org` has access to it.

**Comment by ultraschuppi** [comment]
> What's the long term plan there? Keep things as is, or do we want to (somehow) have these customers migrate to the new plans?

depends on what you mean with long term

final long term is that everything converges towards heat death of the universe ;-)

for something more tangible i do not see a mid term plan to converge everything to the new model. so you better deal with the current situation for some time

hth and sorrey

**Comment by Zelldon** [comment]
supersed by #573
