### ISSUE TITLE
Migrate Testbench to own CC org

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-testbench#533]
Currently testbench runs in a shared Camunda cloud org, where we can reach the limits fast and often don't know whether we can delete clusters etc. 

Ideally we would run testbench in an own Camunda cloud org. @ultraschuppi and me already created one called `Just testbench` https://console.cloud.ultrawombat.com/org/f1155314-5031-4a84-9e29-58f69f8ab242/clusters, which has also its own Sales Plan https://accounts.cloud.ultrawombat.com/salesplans/437af117-c682-4b53-ab3f-603d08f381be (created by Tim).

What we need to do to migrate Testbench:

- [X] Create new Cluster in the  `Just testbench` org (something small) https://console.cloud.ultrawombat.com/org/f1155314-5031-4a84-9e29-58f69f8ab242/cluster/7b2cd3f5-cfcc-4a65-ab22-0ccaa071e68e 
  - [x] Create new credentials for the Zeebe API 
- [x] On org level create credentials  for the Cluster api (creating clusters and generations etc.)
- [X] Adjust the pipeline to deploy the new credentials - most of them are stored in vault https://github.com/zeebe-io/zeebe-cluster-testbench/pull/535
  - [X] Adjust zeebe jenkinsfile, which also access testbench
- [x] Deploy a version and run a QA test 
  - [x] QA https://ci.zeebe.camunda.cloud/job/camunda-cloud/job/zeebe/job/develop/1225/
- [x] Delete the old cluster
- [x] Update medic process https://github.com/zeebe-io/zeebe-medic-process/pull/111
- [x] Update Document of truth
- [x] Search for other occurrences
- [X] Do the same for the Dev cluster
   - [x] In order to test cluster move (fixed via https://github.com/camunda-cloud/console/issues/2819) try cluster move to new org 
   - [x] Create and update client credentials https://github.com/zeebe-io/zeebe-cluster-testbench/pull/538
   - [x] Deploy branch to dev; deploys processes and prints details about generations etc.

**Comment by pihme** [comment]
I think there is also an option to move a cluster to a different org. I never tried it. But in the best case, you just need to move the cluster and can keep all the secrets.

**Comment by ultraschuppi** [comment]
> I think there is also an option to move a cluster to a different org. I never tried it. But in the best case, you just need to move the cluster and can keep all the secrets.

jepp, that should theoretically work. we should try that :) you only need to be
- console:admin
- part of both organizations
- then there is an option to do that in the cluster-details-context menue
- 
![image](https://user-images.githubusercontent.com/6298245/146937188-d8049c5e-e82a-4a22-a23d-2d01f448384b.png)

**Comment by Zelldon** [comment]
Hey @ultraschuppi I tried it unfortunately I seem to have not enough permissions :cry: 

![org](https://user-images.githubusercontent.com/2758593/146937870-09f59b93-63d6-442b-9af0-a8f199d4cc98.png)
No org to select.

@ultraschuppi do you know whether the internal api password/username magic you build together with @pihme works also for other orgs ? The magic to create new generations etc.

**Comment by ultraschuppi** [comment]
> Hey @ultraschuppi I tried it unfortunately I seem to have not enough permissions cry

great! you found a bug! i also have nothing to select. will tackle this in https://github.com/camunda-cloud/console/issues/2819

> 
> ![org](https://user-images.githubusercontent.com/2758593/146937870-09f59b93-63d6-442b-9af0-a8f199d4cc98.png) No org to select.
> 
> @ultraschuppi do you know whether the internal api password/username magic you build together with @pihme works also for other orgs ? The magic to create new generations etc.

this is not related to this. for this we created a dedicated m2m-client in IAM and assigned the necessary permissions for creating generations and what not to it. we can totally do that again

**Comment by Zelldon** [comment]
Nice! Finally I found one :bug: :D Thanks for opening the issue.

> this is not related to this. for this we created a dedicated m2m-client in IAM and assigned the necessary permissions for creating generations and what not to it. we can totally do that again

Awesome than I tried to reuse the credentials thanks!

**Comment by Zelldon** [comment]
Some updates:

 * New testbench seems to be running, it was successfully deployed
 * Deployed all processes
 * QA can run instances
 * Testbench can delete and create clusters and generations

![clusters2](https://user-images.githubusercontent.com/2758593/146945073-18c10ec5-8f41-4d29-9ed8-65e8387b61a9.png)
![clusters](https://user-images.githubusercontent.com/2758593/146945075-158f89ea-e72c-48e6-952c-b3cf9872e3ad.png)

**Comment by Zelldon** [comment]
@pihme do we still need a dev cluster ? :thinking: :D

**Comment by Zelldon** [comment]
If so I will use it as guinea pig for the cluster move

**Comment by Zelldon** [comment]
@ultraschuppi I tried the cluster move, seems to clear all credentials just to let you know :)

![migrate](https://user-images.githubusercontent.com/2758593/146949492-8bebabf2-9b3e-401e-8078-e345223a6bb7.png)
![clients2](https://user-images.githubusercontent.com/2758593/146949496-db0355ce-d459-48ea-9e8c-e60d2f714ff0.png)
![clients](https://user-images.githubusercontent.com/2758593/146949498-01e829dc-1df1-41dc-8b75-9a3430b8e635.png)

**Comment by ultraschuppi** [comment]
> @ultraschuppi I tried the cluster move, seems to clear all credentials just to let you know :)
> 
> ![migrate](https://user-images.githubusercontent.com/2758593/146949492-8bebabf2-9b3e-401e-8078-e345223a6bb7.png) ![clients2](https://user-images.githubusercontent.com/2758593/146949496-db0355ce-d459-48ea-9e8c-e60d2f714ff0.png) ![clients](https://user-images.githubusercontent.com/2758593/146949498-01e829dc-1df1-41dc-8b75-9a3430b8e635.png)

https://github.com/camunda-cloud/console/blob/9e9ac09df6e998d08e1b9de7ee2744397eefce88/backend/controller/cluster.controller.ts#L291-L294

guess there is some history behind that - maybe even a reason.

**Comment by pihme** [comment]
@Zelldon Yes we need the dev cluster and its credentials. You could argue that it can stay where it is given that it is used rarely

**Comment by Zelldon** [comment]
Migration is done :white_check_mark:

**Comment by Zelldon** [comment]
Nightly run worked

![operate-run](https://user-images.githubusercontent.com/2758593/147058058-fabe6748-900c-424b-ae33-4063cad3b842.png)
