### ISSUE TITLE
Do we still need InternalCloudAPIClientFactory

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-testbench#534]
During #533 I was wondering why we have some secrets in vault like:

```

                                      [envVar: 'INTERNAL_CLOUD_CLIENT_SECRET', vaultKey: 'internalCloudClientSecret'],
                                      [envVar: 'INTERNAL_CLOUD_PASSWORD', vaultKey: 'internalCloudPassword'],
```

I tracked the usage until https://github.com/zeebe-io/zeebe-cluster-testbench/blob/develop/internal-cloud-client/src/main/java/io/zeebe/clustertestbench/internal/cloud/InternalCloudAPIClientFactory.java and was wondering whether we still need this or whether this was an left over? @pihme  ?

**Comment by pihme** [comment]
This is how we have access to the APIs to generate generations before a run. I am not aware of any alternative for this. Back then, Console team didn't want to make this available to customers.

**Comment by Zelldon** [comment]
How did you get these values? Do we need to change these on a new org then ?

**Comment by pihme** [comment]
Tim was gracious enough to provide these

**Comment by Zelldon** [comment]
thanks @pihme I will close this then
