### ISSUE TITLE
why do you use Zeebe

### ISSUE THREAD

**Issue by fizz12344321** [zeebe-io/zeebe-cluster-testbench#791]
Hi, I am reading your project and I love this project
I have a question, why do you choose Zeebe in your project instead of others like Camunda, are there any special features that others dont have it. Can you share me it. I am wondering when I should choose Zeebe instead of your project instead of others like Camunda

**Comment by korthout** [comment]
Hi @fizz12344321 👋 Great to hear that you like Zeebe! ❤️ 

🕵️ It seems to me that [this topic](https://forum.camunda.io/search?q=zeebe%20vs%20) has already been discussed a few times on our forums. Please have a look, and let me know in case you're unable to find an answer there.
